# Chapter 1 - Matrix notation & matrix multiplication

## Ex:1 Pg:20

In [19]:
from sympy.abc import u,v,w
import numpy as np
a =np.array([[1 ,1 ,1],[2, 2, 5],[4, 6, 8]])
x=[[u],[v],[w]]
x=np.array(x)
print 'x=\n',x
print 'R2=R2-R1,R3=R3-4*R1'
a[1,:]=a[1,:]-2*a[0,:]
a[2,:]=a[2,:]-4*a[0,:]
print a
print 'R2<->R3'
import numpy as np
def swap_rows(arr, frm, to):
    arr[[frm, to],:] = arr[[to, frm],:]
swap_rows(a,1,2)
print a
print 'The system is now triangular and the equations can be solved by Back substitution'

x=
[[u]
 [v]
 [w]]
R2=R2-R1,R3=R3-4*R1
[[1 1 1]
 [0 0 3]
 [0 2 4]]
R2<->R3
[[1 1 1]
 [0 2 4]
 [0 0 3]]
The system is now triangular and the equations can be solved by Back substitution


## Ex:2 Pg:21

In [20]:
from sympy.abc import u,v,w
import numpy as np
a =np.array([[1, 1, 1],[2, 2, 5],[4, 4, 8]])
print 'a=\n',a
x=[[u],[v],[w]]
x=np.array(x)
print 'x=\n',x
print 'R2=R2-2*R1,R3=R3-4*R1'
a[1,:]=a[1,:]-2*a[0,:]
a[2,:]=a[2,:]-4*a[0,:]
print a
print 'No exchange of equations can avoid zero in the second pivot positon ,therefore the equations are unsolvable'

a=
[[1 1 1]
 [2 2 5]
 [4 4 8]]
x=
[[u]
 [v]
 [w]]
R2=R2-2*R1,R3=R3-4*R1
[[1 1 1]
 [0 0 3]
 [0 0 4]]
No exchange of equations can avoid zero in the second pivot positon ,therefore the equations are unsolvable


# Ex:3 Pg:21

In [21]:
import numpy as np
A=np.array([[2, 3],[4, 0]])
print 'A = \n',A
B=np.array([[1, 2, 0],[5, -1, 0]])
print 'B = \n',B
print 'AB=\n',A.dot(B)

A = 
[[2 3]
 [4 0]]
B = 
[[ 1  2  0]
 [ 5 -1  0]]
AB=
[[17  1  0]
 [ 4  8  0]]


## Ex:4 Pg:22

In [22]:
import numpy as np
A=np.array([[2, 3],[7, 8]])
print 'A=\n',A
P=np.array([[0, 1],[1, 0]])
print 'P(Row exchange matrix)=\n',P
print 'PA=\n',P.dot(A)

A=
[[2 3]
 [7 8]]
P(Row exchange matrix)=
[[0 1]
 [1 0]]
PA=
[[7 8]
 [2 3]]


## Ex:5 Pg:24

In [23]:
import numpy as np
A=np.array([[1, 2],[3, 4]])
print 'A=\n',A
I=np.identity(2)
print 'I=\n',I
print 'IA=\n',I.dot(A)

A=
[[1 2]
 [3 4]]
I=
[[ 1.  0.]
 [ 0.  1.]]
IA=
[[ 1.  2.]
 [ 3.  4.]]


## Ex:6 Pg:25

In [24]:
import numpy as np
E=np.identity(3)
E[1,:]=E[1,:]-2*E[0,:]
print 'E=\n',E
F=np.identity(3)
F[2,:]=F[2,:]+F[0,:]
print 'F=\n',F
print 'EF=\n',E.dot(F)
print 'FE=\n',F.dot(E)
print 'Here,EF=FE,so this shows that these two matrices commute'

E=
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 0.  0.  1.]]
F=
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  1.]]
EF=
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 1.  0.  1.]]
FE=
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 1.  0.  1.]]
Here,EF=FE,so this shows that these two matrices commute


## Ex:7 Pg:25

In [25]:
import numpy as np
E=np.identity(3)
E[1,:]=E[1,:]-2*E[0,:]
print 'E=\n',E
F=np.identity(3)
F[2,:]=F[2,:]+F[0,:]
print 'F=\n',F
G=np.identity(3)
G[2,:]=G[2,:]+G[1,:]
print 'G=\n',G
print 'GE=',G.dot(E)
print 'EG=\n',E.dot(G)
print 'Here EG is not equal to GE,Therefore these two matrices do not commute and shows that most matrices do not commute.'
print 'GFE=\n',G.dot(F.dot(E))
print 'EFG=\n',E.dot(F.dot(G))
print 'The product GFE is the true order of elimation.It is the matrix that takes the original A to the upper triangular U.'

E=
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 0.  0.  1.]]
F=
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  1.]]
G=
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  1.]]
GE= [[ 1.  0.  0.]
 [-2.  1.  0.]
 [-2.  1.  1.]]
EG=
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 0.  1.  1.]]
Here EG is not equal to GE,Therefore these two matrices do not commute and shows that most matrices do not commute.
GFE=
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-1.  1.  1.]]
EFG=
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 1.  1.  1.]]
The product GFE is the true order of elimation.It is the matrix that takes the original A to the upper triangular U.
