# Chapter 8 - Inner product spaces

## Page 271 Example 8.1

In [16]:
import numpy as np
n=np.random.randint(2,9)
a=np.random.rand(1,n)
b=np.random.rand(1,n)
for i in range(0,n):
    a[0,i]=round(a[0,i]*10)
    b[0,i]=round(b[0,i]*10)
print 'n = ',n
print 'a = ',a
print 'b = ',b
print 'Then, (a|b) = \n\n',a*np.transpose(b)

n =  5
a =  [[ 1.  4.  2.  8.  8.]]
b =  [[ 10.   8.   3.   1.   8.]]
Then, (a|b) = 

[[ 10.  40.  20.  80.  80.]
 [  8.  32.  16.  64.  64.]
 [  3.  12.   6.  24.  24.]
 [  1.   4.   2.   8.   8.]
 [  8.  32.  16.  64.  64.]]


## Page 271 Example 8.2

In [17]:
import numpy as np
a=np.random.rand(1,2)
b=np.random.rand(1,2)
for i in range(0,2):
    a[0,i]=round(a[0,i]*10)
    b[0,i]=round(b[0,i]*10)
print 'a = ',a
print 'b = ',b
x1 = a[0,0]#
x2 = a[0,1]#
y1 = b[0,0]#
y2 = b[0,1]#
t = x1*y1 - x2*y1 - x1*y2 + 4*x2*y2#
print 'Then, a|b = ',t

a =  [[ 4.  3.]]
b =  [[ 7.  5.]]
Then, a|b =  47.0


## Page 307 Example 8.28

In [18]:
import numpy as np
print 'x1 and x2  are two real nos. i.e., x1**2 + x2**2 = 1'
x1 = np.random.rand()
x2 = np.sqrt(1 - x1**2)
print 'x1 = ',x1
print 'x2 = ',x2
B = np.array([[x1, x2, 0],[0, 1, 0],[0, 0, 1]])
print 'B = \n',B
print 'Applying Gram-Schmidt process to B:'
a1 = np.array([x1, x2, 0])
a2 = np.array([0 ,1 ,0]) - x2 * np.array([x1 ,x2 ,0])
a3 = np.array([0, 0, 1])
print 'a1 = ',a1
print 'a2 = ',a2
print 'a3 = ',a3
U = np.array([[a1],[a2/x1],[a3]])
print 'U = \n',U
M = np.array([[1, 0, 0],[-x2/x1, 1/x1, 0],[0, 0, 1]])
print 'M = \n',M
print 'inverse(M) * U = ',np.linalg.inv(M) * U
print 'So, B = inverse(M) * U'

x1 and x2  are two real nos. i.e., x1**2 + x2**2 = 1
x1 =  0.383547227589
x2 =  0.923521263539
B = 
[[ 0.38354723  0.92352126  0.        ]
 [ 0.          1.          0.        ]
 [ 0.          0.          1.        ]]
Applying Gram-Schmidt process to B:
a1 =  [ 0.38354723  0.92352126  0.        ]
a2 =  [-0.35421402  0.14710848  0.        ]
a3 =  [0 0 1]
U = 
[[[ 0.38354723  0.92352126  0.        ]]

 [[-0.92352126  0.38354723  0.        ]]

 [[ 0.          0.          1.        ]]]
M = 
[[ 1.          0.          0.        ]
 [-2.40784236  2.60724085  0.        ]
 [ 0.          0.          1.        ]]
inverse(M) * U =  [[[  3.83547228e-01  -4.25822963e-17   0.00000000e+00]
  [  3.54214020e-01   3.54214020e-01   0.00000000e+00]
  [  0.00000000e+00   0.00000000e+00   0.00000000e+00]]

 [[ -9.23521264e-01  -1.76848356e-17   0.00000000e+00]
  [ -8.52891524e-01   1.47108476e-01   0.00000000e+00]
  [ -0.00000000e+00   0.00000000e+00   0.00000000e+00]]

 [[  0.00000000e+00  -0.00000000e+00  

## Page 278 Example 8.9

In [19]:
import numpy as np
#a = round(rand(1,2) * 10)#
a=np.random.rand(1,2)
for j in [0,1]:
    a[0,j]=round(a[0,j]*10)

x = a[0,0]
y = a[0,1]
b = [-y, x]#
print '(x,y) = ',a
print '(-y,x) = ',b
print 'Inner product of these vectors is:'
t = -x*y + y*x#
print '(x,y)|(-y,x) = ',t

print 'So, these are orthogonal.'
print '------------------------------------------'
print 'If inner product is defined as:'
print '(x1,x2)|(y1,y2) = x1y1- x2y1 - x1y2 + 4x2y2'
print 'Then, (x,y)|(-y,x) = -x*y+y**2-x**2+4*x*y = 0 if,'
print 'y = 1/2(-3 + sqrt(13))*x'
print 'or'
print 'y = 1/2(-3 - sqrt(13))*x'
print 'Hence,'
if y == (1./2*(-3 + np.sqrt(13))*x) or (1./2*(-3 - np.sqrt(13))*x):
    print a
    print 'is orthogonal to'
    print b
else:
    print a
    print 'is not orthogonal to'
    print b


(x,y) =  [[ 5.  3.]]
(-y,x) =  [-3.0, 5.0]
Inner product of these vectors is:
(x,y)|(-y,x) =  0.0
So, these are orthogonal.
------------------------------------------
If inner product is defined as:
(x1,x2)|(y1,y2) = x1y1- x2y1 - x1y2 + 4x2y2
Then, (x,y)|(-y,x) = -x*y+y**2-x**2+4*x*y = 0 if,
y = 1/2(-3 + sqrt(13))*x
or
y = 1/2(-3 - sqrt(13))*x
Hence,
[[ 5.  3.]]
is orthogonal to
[-3.0, 5.0]


## Page 282 Example 8.12

In [20]:
import numpy as np
b1 = np.array([3, 0, 4])
b2 = np.array([-1 ,0 ,7])
b3 = np.array([2 ,9 ,11])
print 'b1 = ',b1
print 'b2 = ',b2
print 'b3 = ',b3
print 'Applying the Gram-Schmidt process to b1,b2,b3:'
a1 = b1
print 'a1 = ',a1
a2 = b2-(np.transpose((b2*np.transpose(b1)))/25*b1)
print 'a2 = ',a2
a3 = b3-(np.transpose(b3*np.transpose(b1))/25*b1) - (np.transpose(b3*np.transpose(a2))/25*a2)
print 'a3 = ',a3
print '{a1,a2,a3} are mutually orthogonal and hence forms orthogonal basis for R**3'
print 'Any arbitrary vector {x1,x2,x3} in R**3 can be expressed as:'
print 'y = {x1,x2,x3} = (3*x1 + 4*x3)/25*a1 + (-4*x1 + 3*x3)/25*a2 + x2/9*a3'
x1 = 1#
x2 = 2#
x3 = 3#
y = (3*x1 + 4*x3)/25*a1 + (-4*x1 + 3*x3)/25*a2 + x2/9*a3#
print 'x1 = ',x1
print 'x2 = ',x2
print 'x3 = ',x3
print 'y = ',y
print 'i.e. y = [x1 x2 x3], according to above equation.'
print 'Hence, we get the orthonormal basis as:'

print ',',1./5*a1
print ',',1./5*a2
print 1/9.*a3

b1 =  [3 0 4]
b2 =  [-1  0  7]
b3 =  [ 2  9 11]
Applying the Gram-Schmidt process to b1,b2,b3:
a1 =  [3 0 4]
a2 =  [2 0 3]
a3 =  [2 9 4]
{a1,a2,a3} are mutually orthogonal and hence forms orthogonal basis for R**3
Any arbitrary vector {x1,x2,x3} in R**3 can be expressed as:
y = {x1,x2,x3} = (3*x1 + 4*x3)/25*a1 + (-4*x1 + 3*x3)/25*a2 + x2/9*a3
x1 =  1
x2 =  2
x3 =  3
y =  [0 0 0]
i.e. y = [x1 x2 x3], according to above equation.
Hence, we get the orthonormal basis as:
, [ 0.6  0.   0.8]
, [ 0.4  0.   0.6]
[ 0.22222222  1.          0.44444444]


## Page 283 Example 8.13

In [21]:
import numpy as np
A = np.random.rand(2,2)
A[0,:] = A[0,:] + 1# #so b1 is not equal to zero
a = A[0,0]
b = A[0,1]
c = A[1,0]
d = A[1,1]
b1 = A[0,:]
b2 = A[1,:]
print 'A = ',A
print 'b1 = ',b1
print 'b2 = ',b2
print 'Applying the orthogonalization process to b1,b2:'

a1 = [a, b]
a2 = (np.linalg.det(A)/(a**2 + b**2))*[-np.transpose(b), np.transpose(a)]
print a1,'a1 = '
print a2,'a2 = '
print 'a2 is not equal to zero if and only if b1 and b2 are linearly independent.'
print 'That is, if determinant of A is non-zero.'

A =  [[ 1.25598176  1.81258697]
 [ 0.6193707   0.80341686]]
b1 =  [ 1.25598176  1.81258697]
b2 =  [ 0.6193707   0.80341686]
Applying the orthogonalization process to b1,b2:
[1.255981755902444, 1.8125869670307564] a1 = 
[] a2 = 
a2 is not equal to zero if and only if b1 and b2 are linearly independent.
That is, if determinant of A is non-zero.


## Page 286 Example 8.14

In [22]:
import numpy as np
v = np.array([-10 ,2 ,8])
u = np.array([3, 12, -1])
print 'v = ',v
print 'u = ',u
print 'Orthogonal projection of v1 on subspace W spanned by v2 is given by:'
a = (np.transpose(u*np.transpose(v)))/(u[0]**2 + u[1]**2 + u[2]**2) * u
print a
print 'Orthogonal projection of R**3 on W is the linear transformation E given by:'
print '(x1,x2,x3) -> (3*x1 + 12*x2 - x3)/%d * (3 12 -1)',(u[0]**2 + u[1]**2 + u[2]**2)
print 'Rank(E) = 1'
print 'Nullity(E)  = 2'

v =  [-10   2   8]
u =  [ 3 12 -1]
Orthogonal projection of v1 on subspace W spanned by v2 is given by:
[-3  0  1]
Orthogonal projection of R**3 on W is the linear transformation E given by:
(x1,x2,x3) -> (3*x1 + 12*x2 - x3)/%d * (3 12 -1) 154
Rank(E) = 1
Nullity(E)  = 2


## Page 288 Example 8.15

In [23]:
from sympy.mpmath import quad,cos,sin,pi,sqrt

#part c
print 'f = (sqrt(2)*cos(2*pi*t) + sqrt(2)*sin(4*pi*t))**2'
print 'Integration (f dt) in limits 0 to 1 = ',
x0 = 0#
x1 = 1#
X = quad(lambda t:(sqrt(2)*cos(2*pi*t) + sqrt(2)*sin(4*pi*t))**2,[x0,x1])
print X

f = (sqrt(2)*cos(2*pi*t) + sqrt(2)*sin(4*pi*t))**2
Integration (f dt) in limits 0 to 1 =  2.0


## Page 294 Example 8.17

In [24]:
import numpy as np
#Equation given in example 14 is used.
def transform(x,y,z):
    x1 = 3*x#
    x2 = 12*y#
    x3 = -z#
    m = [x1 ,x2, x3]
    return m

print 'Matrix of projection E in orthonormal basis is:'
t1 = transform(3,3,3)#
t2 = transform(12,12,12)#
t3 = transform(-1,-1,-1)#
A = np.vstack([t1,t2,t3])#[t1# t2# t3]#
print 'A = 1/154  *  ',A

A1 = np.transpose(np.conj(A))
print 'A* = ',A1
print 'Since, E = E* and A = A*, then A is also the matrix of E*'
a1 = [154, 0, 0]#
a2 = [145 ,-36, 3]#
a3 = [-36 ,10 ,12]#
print 'a1 = ',a1
print 'a2 = ',a2
print 'a3 = ',a3
print '{a1,a2,a3} is the basis.'
Ea1 = [9 ,36 ,-3]#
Ea2 = [0 ,0, 0]#
Ea3 = [0 ,0 ,0]#
print 'Ea1 = ',Ea1
print 'Ea2 = ',Ea2
print 'Ea3 = ',Ea3
B = np.array([[-1, 0, 0],[-1, 0 ,0],[0, 0, 0]])
print 'Matrix B of E in the basis is:'
print 'B = \n',B
B1 = np.transpose(np.conj(B))
print 'B* = \n',B1
print 'Since, B is not equal to B*, B is not the matrix of E*'

Matrix of projection E in orthonormal basis is:
A = 1/154  *   [[  9  36  -3]
 [ 36 144 -12]
 [ -3 -12   1]]
A* =  [[  9  36  -3]
 [ 36 144 -12]
 [ -3 -12   1]]
Since, E = E* and A = A*, then A is also the matrix of E*
a1 =  [154, 0, 0]
a2 =  [145, -36, 3]
a3 =  [-36, 10, 12]
{a1,a2,a3} is the basis.
Ea1 =  [9, 36, -3]
Ea2 =  [0, 0, 0]
Ea3 =  [0, 0, 0]
Matrix B of E in the basis is:
B = 
[[-1  0  0]
 [-1  0  0]
 [ 0  0  0]]
B* = 
[[-1 -1  0]
 [ 0  0  0]
 [ 0  0  0]]
Since, B is not equal to B*, B is not the matrix of E*
